replicaCount: 2

image:
  repository: tiagovedana/hello-k8s
  tag: staging
  pullPolicy: IfNotPresent

app:
  name: hello-world-staging
  port: 5000
  env: staging

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  pathType: Prefix
  host: hello-world-staging.tvedana.com