apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-k8s.fullname" . }}-svc
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}